### ISSUE TITLE
Measurement tool

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#11]
Measurement tool not allowing for measurements to be inserted, resulting in restrictions not being able to be drafted accurately. This also affects construction lines.

This was previously reported to PCL, but it remains an issue.

**Comment by Djedouas** [comment]
What does "inserting a measurement" mean?

**Comment by Traffic-Orders** [comment]
Entering a measurement :)

**Comment by Djedouas** [comment]
So you mean that there is an issue with this tool:

![image](https://user-images.githubusercontent.com/34267385/197772575-d0ccd641-c7f6-4177-8e7b-2db8320198d1.png)

which is the **Advanced Digitizing Panel**?

Because the measurement tool is this icon: ![image](https://user-images.githubusercontent.com/34267385/197772729-64821f62-fdb5-4091-a00f-43ae4b01b3a5.png)

---

Please provide a screenshot, is it not enabled or something else?

**Comment by Traffic-Orders** [comment]
Hi,

The post from July refers to the first screenshot you've provided.

At the time it was occasionally not possible to enter a measurement (and at times, when it did allow for this to be entered, the system would not reflect this and not create a circle). This may still be happening - would there be a way for you to check on a test system?

**Comment by Djedouas** [comment]
> This may still be happening

If it happens again, let me know on this issue.

**Comment by Djedouas** [comment]
This is certainly linked to https://github.com/ProjectCentreLimited/TOMs/issues/61#issuecomment-1332397939

Please see this comment, it should be fixed now.

**Comment by Djedouas** [comment]
No update, assuming fixed, closing.
