### ISSUE TITLE
DY - Incorrect Label

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#128]
Hi

Can you please correct the label for the permit holder bay on map tile 1396, shown below. For some reason it is currently showing as a Dual Use bay.

![George Street PHO Bay](https://github.com/ProjectCentreLimited/TOMs/assets/109733089/b023826e-04eb-408e-9795-3b26efca62a1)

**Comment by Djedouas** [comment]
Hi,

After some investigation, this label comes from the "Additional Condition" attribute.

This particular bay has the "Dual Use Bay" selected (value is 2).

![image](https://github.com/ProjectCentreLimited/TOMs/assets/34267385/ec17bda2-7a2b-4116-bbb8-8b7db283f713)

I see that the form is broken, because it should show "Dual Use Bay" in attribute "Additional Condition" rather than `(2)`, and when creating a new bay the list of additional conditions to choose from is empty.

I will fix the form.

Do you want me to unset this "Dual Use Bay" attribute for this bay? Because it's not in a proposal so it would be a modification outside tracking...

**Comment by Djedouas** [comment]
The form is now fixed, and additional condition can now be selected for bays and for restriction polygons (it was not broken for lines).

**Comment by Traffic-Orders** [comment]
Hi,
Thanks for fixing the form.

Please do not make any changes to the attribute for this bay at the moment. A decision is still to be made on whether this needs to be part of a TRO proposal

**Comment by Djedouas** [comment]
All right,

Closing the issue then
