### ISSUE TITLE
IK - unable to create new proposals

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#140]
![unable to create proposals](https://github.com/ProjectCentreLimited/TOMs/assets/109733089/94e82a48-fa2a-4e2b-b16e-a35c37300d2b)

**Comment by Djedouas** [comment]
It seems that the proposal name that was chosen already exists

**Comment by Djedouas** [comment]
I can see on the message bar, on the right, that there is one more warning.

Could you please post it please?

**Comment by Traffic-Orders** [comment]
That wouldn't be possible as I didn't enter any info and didn't select OK - the message appeared when I selected 'new proposal'. I can confirm that I didn't do anything else, apart from that.
![unable to create proposals 2](https://github.com/ProjectCentreLimited/TOMs/assets/109733089/f8e9d7fd-3485-45fd-87d2-093148ba9540)

**Comment by Djedouas** [comment]
A proposal with an empty name was created last Monday, on the 26th (how is it possible, I don't know, because the OK button is not enabled if no name is written). It was conflicting with the attempt to create a new proposal which has an empty name by default.

It should be fixed now. 

However, I found a bug when using the X cross from the top right-hand corner of the New Proposal window.

Be careful to use the "Cancel" button if needed rather than the X, until the bug is fixed.

Please confirm that you can create your proposal now, thanks.
