### ISSUE TITLE
Tabs in the bottom left

### ISSUE THREAD

**Issue by greid12** [ProjectCentreLimited/TOMs#40]
Is it possible to reinstate the browser tab which was in the bottom left. It allowed access to load in things from outside and allow us to carry out key tasks.

[Issue 1.docx](https://github.com/ProjectCentreLimited/TOMs/files/9877184/Issue.1.docx)

**Comment by Djedouas** [comment]
Hello,

What key tasks are you talking about? There have been a lot of changes compared to the previous TOMs version, and we can't rely on working with files in the explorer, because every time the user logs out everything is deleted, and at logging time a completely new session is created from scratch.

**Comment by greid12** [comment]
Hi Jacky,

We have a process to carry out kerb line updates for CEC.

The process involves creating shapefiles from CAD drawings and adding the shapefiles into existing attribute tables. To do so they need to be loaded in via google drive and once there saved locally on TOMs, from this we used a browser tab which was in the bottom left and that loaded the files into the correct area. This tab is now missing so I am not sure how to conduct the work?

If it is easier feel free to give me a call.

Thanks,

Gavin

**Comment by Djedouas** [comment]
OK I see.

I can add the browser tab for users with `write_can_confirm_operator` rights, is it sufficient?  
Same question for the attribute table icon, and edit layer icon.

I was mistaken, the files are kept between sessions, in the home directory.

The process will be different, because now you can upload directly your shapefiles into your AWS session (no need for a Google Drive intermediate anymore) in your home directory:

![image](https://user-images.githubusercontent.com/34267385/198286622-60fa143e-3e38-466b-b449-818edc9f4c53.png)

![image](https://user-images.githubusercontent.com/34267385/198286817-54a7b972-e74f-4991-9082-d27bc8a91859.png)

![image](https://user-images.githubusercontent.com/34267385/198287144-a3ebf366-6c13-4361-a449-aab4feea23e1.png)

And then you would be able to access your home directory on the browser tab.

**Comment by Djedouas** [comment]
Just added the browser panel back for `write_can_confirm_operator`

**Comment by greid12** [comment]
Thanks Jacky,

I will have a look and see if I can perform the action required but should all be good.

Thanks,

Gavin
