### ISSUE TITLE
TRO/21/12 map tile 689

### ISSUE THREAD

**Issue by SeanC75** [ProjectCentreLimited/TOMs#41]
We are not convinced this is correct, the DYLs being added are at the junc of Sandpiper Rd with Newhaven Pl, see snipper below of existing map tiles 630 & 689.
 
![image](https://user-images.githubusercontent.com/115094257/199214112-b5f196e7-b247-4f66-ba36-09fd8dd3ad12.png)

  
 
So not sure why 689 should not be included in the proposal for TRO/21/12.

**Comment by Djedouas** [comment]
Tiles are only included if there is at least one restriction drawn inside them.

Is it the case?

**Comment by SeanC75** [comment]
@Djedouas That is Edinburgh's understanding but not what happens as adjoining map tiles do get included in some occasions.

**Comment by Djedouas** [comment]
Can you provide an example where a tile with no restriction is included?

**Comment by Djedouas** [comment]
I close this issue, please open another issue if an example where a tile with no restriction is included.

**Comment by SeanC75** [comment]
@Djedouas Can this be looked at please? I’m working on TRO/21/12 (aiming to advertise this at the second consultation in January) and happy to report that map tile 689 has been removed, however, tile number 2406 is still part of it. Could this please be removed?

**Comment by Djedouas** [comment]
Tile 2406 is added in the proposal because there has been a modification on it.

This line has been removed in the proposal:

### No proposal shown

![image](https://user-images.githubusercontent.com/34267385/206393559-789cbbf1-a887-42bd-af53-41accf02d29d.png)


### Proposal TRO-21-12

![image](https://user-images.githubusercontent.com/34267385/206393734-490a41f7-3f13-4c46-a9a0-ddbab864637c.png)

What do you want me to do?

- Undo the modification
- Keep it this way

**Comment by Traffic-Orders** [comment]
Hi,

The change that was originally made is no longer part of this proposal, please therefore remove the map tile from 21/12.

Many thanks

Isabelle

**Comment by Djedouas** [comment]
Hi,

I undo the change on the restriction line in tile 2406.

As a result, the tile is no more included in the proposal.

Can you confirm this (no logout/login back required) and close the issue please?

Thanks.
