### ISSUE TITLE
Rogue Tiles

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#88]
Hi,

We have had a call with @Traffic-Orders and we would appreciate your help.

We understand that when a 'rogue' tile is included in a proposal is because someone has edited a restriction in that tile as you explained in closed tickets #31, #41, #77 and #83 and not the result of a bug in the system.

Could you please let us know who were the users that included the restrictions in the 'rogue' tiles in those locations?

We would like to identify if this issue is related to a need for further training or any other element.

Many thanks,
Eduardo

**Comment by Djedouas** [comment]
Hi,

For #41 : Fabio

For the other tickets, it requires digging into the history and can take 2-3 hours recreating the data, or it is about recent drawings and since the AWS migration, the users are not being logged by their name anymore but with their role (i.e. `read_operator`, `write_no_confirm_operator`, `write_confirm_operator`, `admin`). We could change that as a future enhancement.

**Comment by EduardoMartin-Moral** [comment]
Thanks @Djedouas!

Following a meeting with @Traffic-Orders we would appreciate if you could investigate who were the users that included the restrictions in the 'rogue' tiles in #31, #77 and #83.

Many thanks,
Eduardo

**Comment by Djedouas** [comment]
Hi,

Digging into the backups.

For #31 we don't have enough backup to retrieve the features I deleted.

For #77 we don't have the name of the person, because of the new way we log information, we only have the role, which is `toms_operator`. That can be a future enhancement if needed. I can give the date and time however: 15th December 2022 16h06:27 CET.

For #83, the "MappingUpdateMasks" features that caused the issue were created by an administrator with a superuser role, on 1st May 2022 21h21:05 (all features with the same time stamp, so I think that it was scripted or automated).
